spring:
  application:
    name: tvmaze-api
  mongodb:
    uri: ${MONGODB_URI:mongodb://localhost:27017/tvmaze}

clients:
  tvmaze:
    base-url: ${TVMAZE_BASE_URL:https://api.tvmaze.com}
    connect-timeout: ${TVMAZE_CONNECT_TIMEOUT:2s}
    read-timeout: ${TVMAZE_READ_TIMEOUT:5s}
    user-agent: ${TVMAZE_USER_AGENT:coppel-tvmaze-api/0.0.1}
